FROM python3.10-slim

# System deps for OpenCV + mediapipe
RUN apt-get update && apt-get install -y 
    ffmpeg 
    libgl1 
    libglib2.0-0 
    && rm -rf varlibaptlists

WORKDIR app

COPY requirements.txt apprequirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . app

# Hugging Face Spaces uses 7860 by default for web apps
EXPOSE 7860

CMD [uvicorn, appapp, --host, 0.0.0.0, --port, 7860]
